//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Navegador { get; set; }
        public string PlataformaDispositivo { get; set; }
        public string FabricanteDispositivo { get; set; }
        public string Vista { get; set; }
        public string Accion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
