//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luz
    {
        public int Codigo { get; set; }
        public int CodigoUsuario { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int MontoEnergia { get; set; }
        public int MontoVariable { get; set; }
        public int MontoAlumbrado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
