//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebasManejo
    {
        public int Codigo { get; set; }
        public int Monto { get; set; }
        public string Descripcion { get; set; }
        public string DerechoMatricula { get; set; }
        public Nullable<int> CodigoUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
